### ISSUE TITLE
system tests: write basic producer tests

### ISSUE THREAD

**Issue by marclop** [elastic/apm-queue#93]
## Description

We MUST ensure that both producers can produce a set number of events to a topic, and are routed according to an `apmqueue.TopicRouter`.

```[tasklist]
### Tasks
- [ ] Synchronous producing of N records
- [ ] Asynchronous producing of N records
- [ ] Messages are routed based on some model.APMEvent fields.
```

## Related issues

Depends on #92
